### ISSUE TITLE
IE10

### ISSUE THREAD

**Issue by Mohit180691** [devoopsme/devoops#38]
Showing access denied error in IE10. but working fine firefox

**Comment by CyberianIce** [comment]
My instances works with IE8+. Only thing you should consider is that this template can only by served by httpd due to ajax page loader. This is caused by browser limitation to respond on xHRs only within same domain origin, due to security policy of most browsers (but not firefox). Therefore you can't open index.html from local folder, but You have to upload to web serer instead.

**Comment by nnmware** [comment]
Thanks for answer. We fully agree.

**Comment by devoopsme** [comment]
Thanks for answer. We fully agree.
